### ISSUE TITLE
install jq command on jenkins deployment 

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/common_scripts#1]
Hello @fuchicorp/devops ,

Please install jq command on our jenkins server. We will run the following script on jenkins. Please let us know if you have any questions.

Thank you 

https://github.com/fuchicorp/common_scripts/blob/9fc6716e6d853f04da4e16ed0548ecb2c5679b4d/github-management/get-listof-members.sh#L11

**Comment by fsadykov** [comment]
I just want to point that jq command should be installed permanently. We have to make sure that jq command installed  inside the docker image

**Comment by NadiraSaip** [comment]
@fsadykov @SharifAbdulcoder Please grant me access to centos_jenkins repo. Thanks

**Comment by fsadykov** [comment]
> @fsadykov @SharifAbdulcoder Please grant me access to centos_jenkins repo. Thanks

You are on admin team you should be able to access now

**Comment by fsadykov** [comment]
Hello,

This ticket is not done. Would you please take a look? 

```
╰─() k exec -ti jenkins-fuchicorp-deployment-cfc44bdf8-jlbp6 -n tools -- bash                                                                    127 ↵
[root@jenkins-fuchicorp-deployment-cfc44bdf8-jlbp6 /]# jq
bash: jq: command not found
```
